names:
- mikado
- kinder_pingui
- kinder_country
- kinder_tronky
- tic_tac
- sucette
- capsule
- pepito
- bouteille_plastique
- canette
nc: 10
path: C:\DEV\_ia_cnam\ia-cours-4\datasets/structured
test: C:\DEV\_ia_cnam\ia-cours-4\datasets/structured/images/test
train: C:\DEV\_ia_cnam\ia-cours-4\datasets/structured/images/train
val: C:\DEV\_ia_cnam\ia-cours-4\datasets/structured/images/val
